### ISSUE TITLE
Error install  requirements.txt : llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"

### ISSUE THREAD

**Issue by amscosta** [HandsOnLLM/Hands-On-Large-Language-Models#6] opened 2024-09-20 12:23 UTC
Hello Guys,
Congratulations on this excellent book.
Trying to install, I got the following error in the llama_cpp line of the requirements.txt :
(Hands-On-Large-Language-Models-env) c0274@c0274-i7:~/Hands-On-Large-Language-Models$ pip install -r requirements.txt
Usage: pip [options]

ERROR: Invalid requirement: llama_cpp_python == 0.2.78 -C cmake.args="-DLLAMA_BLAS=ON"
pip: error: no such option: -C

Any workaround is very welcome.
Thanks.

**Comment by negativenagesh** [comment] 2024-09-21 18:40
Hello @amscosta ,
specify where have you tried installing this exactly..

1. The arguments cmake.args="-DLLAMA_BLAS=ON" are meant for cmake during the package building process, but pip does not recognize -C as a valid option.

Check out -C, why and where its used.  [Link](https://cmake.org/cmake/help/latest/manual/cmake.1.html)
-C <initial-cache>
Pre-load a script to populate the cache. When CMake is first run in an empty build tree, it creates a CMakeCache.txt file and populates it with customizable settings for the project. This option may be used to specify a file from which to load cache entries before the first pass through the project's CMake listfiles. The loaded entries take priority over the project's default values. The given file should be a CMake script containing [set()](https://cmake.org/cmake/help/latest/command/set.html#command:set) commands that use the CACHE option, not a cache-format file.

try running this locally, this should work for your problem--

    `pip install llama_cpp_python==0.2.78 --config-settings cmake-args="-DLLAMA_BLAS=ON"`

2. I downloaded the [requirements.txt](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/requirements.txt), and uploaded it to googlecolab and ran - 
`%pip install -r requirements.txt`
got the output - 

 Collecting llama_cpp_python==0.2.78 (from -r requirements.txt (line 30))
   Downloading llama_cpp_python-0.2.78.tar.gz (50.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 MB 14.8 MB/s eta 0:00:00

**Comment by amscosta** [comment] 2024-09-22 20:04
Hello,
Still not working. Thanks.
![Screenshot from 2024-09-22 16-58-17](https://github.com/user-attachments/assets/5115b16a-32ae-4415-84bf-4b995028c657)

**Comment by amscosta** [comment] 2024-09-22 20:17
Trick done. Thanks.
![Screenshot from 2024-09-22 17-16-28](https://github.com/user-attachments/assets/dc684e93-8f96-46d9-8ded-9bba47b55b24)

**Comment by amscosta** [comment] 2024-09-22 20:18
cmakeDOTargs

**Comment by negativenagesh** [comment] 2024-09-23 01:08
Close the issue if you're satisfied

**Comment by MaartenGr** [comment] 2024-09-23 06:48
Thank you all for helping out! Glad to hear that the issue is resolved.

**Closed by MaartenGr** 2024-09-23 06:48 UTC

**Comment by negativenagesh** [comment] 2024-09-29 16:37
> MaartenGr

Hello @MaartenGr, I would really appreciate if you marked my above conversation as --> 'Marked as an answer' because the person who opened the issue have satisfied i think..

**Comment by MaartenGr** [comment] 2024-09-29 16:59
@negativenagesh Although I appreciate the help on this, it is not how issues work. You cannot check the conversation as "Marked as an answer". That is something that only applies to discussions. Note that this also relates to the conversation we had previously where the underlying problem was an old installation of pip.

**Comment by negativenagesh** [comment] 2024-09-29 17:13
Thank you @MaartenGr for you time and sharing this, I'm new to open source..

**Comment by MaartenGr** [comment] 2024-09-29 17:17
@negativenagesh No problem! I'm here to help. If you have any questions regarding the process of doing open source, feel free to reach out.

**Comment by negativenagesh** [comment] 2024-09-29 17:35
@MaartenGr 

Thank you.. will definitely ask if anything pops up..

I have made changes in pull request https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/pull/8/commits/c58b336297b424da523304963c897ebde8768eec can you please check and review, that would be helpful...
